[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[profile.default.metadata]
bytecode_hash = "ipfs"

[profile.ci]
fuzz = { runs = 10000 }

[profile.lite]
optimizer = false

via_ir = false
